export const REDUX_NAME={
    SET_LOGIN_SCREEN:'SET_LOGIN_SCREEN',
    SET_VERIFY_OTP:'SET_VERIFY_OTP',
    SET_GOOGLE_SIGN_IN:'SET_GOOGLE_SIGN_IN',
    SET_FACEBOOK_SIGN_IN:'SET_FACEBOOK_SIGN_IN',
    SET_SEND_OTP:'SET_SEND_OTP'
}